#!/usr/bin/octave
% NOTE: This line must be edited to point to your octave executable

%################################################################################
%#
%#      This file is a component of the volcanic infrasound monitoring software
%#      written at the U.S. Geological Survey by Hans F. Schwaiger (hschwaiger@usgs.gov)
%#      and Alexandra M. Iezzi (amiezzi@alaska.edu).  These programs relies on tools
%#      developed for the ash transport and dispersion model Ash3d, written at the
%#      U.S. Geological Survey by Hans F. Schwaiger (hschwaiger@usgs.gov), Larry G.
%#      Mastin (lgmastin@usgs.gov), and Roger P. Denlinger (roger@usgs.gov).
%#
%#      The model and its source code are products of the U.S. Federal Government and therefore
%#      bear no copyright.  They may be copied, redistributed and freely incorporated 
%#      into derivative products.  However as a matter of scientific courtesy we ask that
%#      you credit the authors and cite published documentation of this model (below) when
%#      publishing or distributing derivative products.
%#
%#      Schwaiger, H.F., Alexandra M. Iezzi and David Fee;
%#         AVO-G2S:  A modified, open-source Ground-to-Space atmospheric specifications
%#           for infrasound model; Computers and Geosciences, v125, p90-97, 2019,
%#           doi:10.1016/j.cageo.2018.12.013
%#
%#      We make no guarantees, expressed or implied, as to the usefulness of the software
%#      and its documentation for any purpose.  We assume no responsibility to provide
%#      technical support to users of this software.
%
%###############################################################################
%#
%#  plot_tloss2d.m
%#
%#  This octave script gennerates a range-altitude transmission loss plot along a profile
%#  for Modess, ePape and other forward model outputs from ncpaprop.  This script is
%#  intended to be run after run_InfraTool.sh since it relies on variables being passed
%#  through temporary files generated by that script.  Expected files are:
%#   1) yyyy.dat    year of event            (YYYY)
%#   2) mm.dat      month of event           (MM)
%#   3) dd.dat      day of event             (DD)
%#   4) hh.dat      hour of event            (HH one of 00,06,12,18,24)
%#   5) srcx.dat    longitude of source      (real valued in range 0.0-360.0)
%#   6) srcy.dat    latitude of source       (real valued in range -90.0-90.0)
%#   7) srcz.dat    altitude of source       (real valued in km)
%#   8) az1.dat     azimuth of start profile (real valued in range 0.0-360.0)
%#   9) modelid.dat model ID                 (integer)
%#  10) rng.dat     nange of reciever        (real valued (km) in range 0.0-1000.0)
%#  11) freq.dat    frequency of source      (real valued in Hz, 0.1-1.0)
%#  12) srcname.dat name of source/volcano   (no white spaces)
%#  Output is the file temp.png
%#
%###############################################################################


clear all;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
yyyy=load('yyyy.dat');
mm  =load('mm.dat');
dd  =load('dd.dat');
hh  =load('hh.dat');
srcx=load('srcx.dat');
srcy=load('srcy.dat');
srcz=load('srcz.dat');
az1 =load('az1.dat');
nmethid=load('modelid.dat');
rng =load('rng.dat');
freq=load('freq.dat');
srcname=textread('srcname.dat','%s');

MM=num2str(mm,'%02.f');
DD=num2str(dd,'%02.f');
HH=num2str(hh,'%02.f');

if nmethid == 5
  NMeth  = 'Stratified-Modess';  pref='tloss';      sufx='nm';
elseif nmethid == 6
  NMeth  = 'Stratified-CModess'; pref='tloss';      sufx='cnm';
elseif nmethid == 7
  NMeth  = 'Stratified-WMod';    pref='wtloss';     sufx='nm';
elseif nmethid == 8
  NMeth  = 'ModBB';    pref='';     sufx='';
  exit
elseif nmethid == 9
  NMeth  = 'RngDep-Modess'; pref='tloss_rd';   sufx='nm';
elseif nmethid == 10
  NMeth  = 'RngDep-pape';   pref='tloss';      sufx='pe';
else
  'No model given'
  exit
end

dim1='_1d.';
dim2='_2d.';

file1=sprintf('%s%s%s',pref,dim1,sufx);
file2=sprintf('%s%s%s',pref,dim2,sufx);
file3=sprintf('%s%slossless.%s',pref,dim1,sufx);
dat1=load(file1);
dat2=load(file2);
if exist(file3)==2
  HasLossless = 1;
  dat3=load(file3);
else
  HasLossless = 0;
end

r1=dat1(:,1);
nr=max(size(dat1));
nc=min(size(dat1));
tl1_Re=dat1(:,2);
tl1_Im=dat1(:,3);
tl1=10*log10(tl1_Re.^2 + tl1_Im.^2);
if nc>3
  IsStrat=1;
  inco=10*log10(dat1(:,4).^2);
else
  IsStrat=0;
end

r2=dat2(:,1);
z2=dat2(:,2);
tl2_Re=dat2(:,3);
tl2_Im=dat2(:,4);
tl2=10*log10(tl2_Re.^2 + tl2_Im.^2);

if HasLossless == 1
  r3=dat3(:,1);
  tl3_Re=dat3(:,2);
  tl3_Im=dat3(:,3);
  tl3=10*log10(tl3_Re.^2 + tl3_Im.^2);
end

nz=max(size(dat2))/nr;
R2 =reshape(r2,nz,nr);
Z2 =reshape(z2,nz,nr);
TL2=reshape(tl2,nz,nr);

fig1=figure;
subplot(10,1,2:6),imagesc(R2(1,:),Z2(:,1),TL2,[-130 -80]);hold on;
plot(rng,0,'g^','markerfacecolor','g','MarkerSize',8)
ylabel('Altitude (km)')
set(gca,'XTick',[])
titstr=sprintf('%s : 2d transmission loss: %.2f Hz\n%i-%s-%s %s:00 UTC\nSource=%s, Az=%0.1f',NMeth,freq,yyyy,MM,DD,HH,srcname{1},az1);
title(titstr);
axis xy;
h=colorbar('SouthOutside');
xlabel(h, 'Tloss (Db)')
colormap(flipud(hot));
hold off;
subplot(10,1,8:10),plot(r1,tl1,'r-'); hold on;
if HasLossless == 1
  subplot(10,1,8:10),plot(r3,tl3,'b-');
end
if IsStrat==1
  subplot(10,1,8:10),plot(r1,inco,'g-');
end
% Now sort out legend
if HasLossless == 1 && IsStrat==1
  legend('lossy','lossless','incoher.');
elseif HasLossless == 1 && IsStrat==0
  legend('lossy','lossless');
else
  legend('lossy');
end


xlabel('Range (km)')
ylabel('Tloss (Db)');
hold off;

outfilename=sprintf('%s_%s_Az%0.1f_%.2fHz_%i%s%s%sZ.png',srcname{1},NMeth,az1,freq,yyyy,MM,DD,HH);
print(outfilename,'-dpng')
print -dpng temp.png


